### ISSUE TITLE
'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by jedStevens** [orf/gping#11]
I get this error when I try to run `gping` on 64 bit Arch Linux.

    Traceback (most recent call last):
      File "/usr/bin/gping", line 11, in <module>
        sys.exit(run())
      File "/usr/lib/python3.5/site-packages/gping/pinger.py", line 251, in run
        for ping in it(url):
      File "/usr/lib/python3.5/site-packages/gping/pinger.py", line 225, in _linux
        yield round(float(linux_re.search(line).group(1)))
    AttributeError: 'NoneType' object has no attribute 'group'

**Comment by KoesterD** [comment]
Seems to be the same error as in #2

**Comment by jedStevens** [comment]
Fixed with the solution from #2
