### ISSUE TITLE
Doesn't work with python 2.7

### ISSUE THREAD

**Issue by buriy** [orf/gping#18]
```
$ gping
Traceback (most recent call last):
  File "/usr/local/bin/gping", line 9, in <module>
    load_entry_point('pinggraph==0.0.9', 'console_scripts', 'gping')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/gping/pinger.py", line 89
    def line(self, from_: P, to: P, paint=None, character=None):
                        ^
SyntaxError: invalid syntax
```
and
```
Traceback (most recent call last):
  File "/usr/local/bin/gping", line 9, in <module>
    load_entry_point('pinggraph==0.0.9', 'console_scripts', 'gping')()
  File "/usr/local/lib/python2.7/dist-packages/gping/pinger.py", line 293, in run
    _run()
  File "/usr/local/lib/python2.7/dist-packages/gping/pinger.py", line 288, in _run
    print("\n".join(c.process_colors()))
  File "/usr/local/lib/python2.7/dist-packages/gping/pinger.py", line 138, in process_colors
    r.write(d)
TypeError: unicode argument expected, got 'str'
```

**Comment by orf** [comment]
I've pushed a new release, can you try it out? I'm not sure what to do about the encoding errors, I'm tempted to just say "screw it use Python 3".

**Comment by buriy** [comment]
Thanks, it works great now!
