### ISSUE TITLE
Encoding issue [Win10-x64]

### ISSUE THREAD

**Issue by sandwwraith** [orf/gping#19]
My system language is russian, so terminal codepage is 866. When i'm trying to run script, i get:
`Traceback (most recent call last):
  File "C:\Anaconda\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda\Scripts\gping.exe\__main__.py", line 9, in <module>
  File "C:\Anaconda\lib\site-packages\gping\pinger.py", line 294, in run
    _run()
  File "C:\Anaconda\lib\site-packages\gping\pinger.py", line 281, in _run
    for ping in it(url):
  File "C:\Anaconda\lib\site-packages\gping\pinger.py", line 227, in _windows
    line = ping.stdout.readline().decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 0: invalid start byte`

If change decode() to decode('CP866') or decode('win-1251') it works, but outputs nothing.  (And i can't found where to change output encoding). Solution is to run `chcp 65001` before executing script. Maybe add this to script by default? (But i don't know how exactly to do this, because `subprocess.Popen(["chcp","65001"])` doesn't work - seems that `chcp` is not executable file.)

**Comment by sandwwraith** [comment]
I found: it's possible to use `subprocess.call("chcp 65001",shell=True)` to change terminal codepage within python. If write it before opening `ping` subprocess, all works well

**Comment by Oxicode** [comment]
+1
