### ISSUE TITLE
Small latency causes division by zero

### ISSUE THREAD

**Issue by valneacsu** [orf/gping#36]
If you ping the default gateway over a low latency medium (LAN) you get latencies that result in a division by zero:
```
$ gping 192.168.1.1
Traceback (most recent call last):
  File "/mnt/Stuff/workplace/python/pinggraph/bin/gping", line 11, in <module>
    sys.exit(run())
  File "/mnt/Stuff/workplace/python/pinggraph/local/lib/python2.7/site-packages/gping/pinger.py", line 305, in run
    _run()
  File "/mnt/Stuff/workplace/python/pinggraph/local/lib/python2.7/site-packages/gping/pinger.py", line 331, in _run
    plotted = plot(width, height, buff, host)
  File "/mnt/Stuff/workplace/python/pinggraph/local/lib/python2.7/site-packages/gping/pinger.py", line 149, in plot
    yellow_zone_idx = round(max_scaled * (100 / max_ping))
ZeroDivisionError: float division by zero
```

**Comment by valneacsu** [comment]
It seems that this issue was fixed already in https://github.com/orf/gping/commit/413394de6bfa6d2b734f524f2111f6a77798d6c6. The downstream package does not yet include this fix though, so it may be worth it to release.

Closing the issue.
