### ISSUE TITLE
gping crash when latency is 0 ms

### ISSUE THREAD

**Issue by SlimG** [orf/gping#39]
When I try to ping a local address, I sometimes get 0 ms, and thus gping crashes with the following errormessage:

```
robert@ubuntu:~$ gping 192.168.0.2
Traceback (most recent call last):
  File "/home/robert/.local/bin/gping", line 11, in <module>
    sys.exit(run())
  File "/home/robert/.local/lib/python3.5/site-packages/gping/pinger.py", line 305, in run
    _run()
  File "/home/robert/.local/lib/python3.5/site-packages/gping/pinger.py", line 331, in _run
    plotted = plot(width, height, buff, host)
  File "/home/robert/.local/lib/python3.5/site-packages/gping/pinger.py", line 149, in plot
    yellow_zone_idx = round(max_scaled * (100 / max_ping))
ZeroDivisionError: division by zero
```

I restart gping a few times until the first echo response takes 1 or more ms, then gping starts and works as expected.

**Comment by orf** [comment]
Hi, this should be fixed in a new release I just pushed. Please update! 👍
