### ISSUE TITLE
Crashes when window is resized too small

### ISSUE THREAD

**Issue by kn100** [orf/gping#48]
Steps to reproduce: Start gping, resize terminal window vertically until it is very small.

Traceback (most recent call last):
  File "/snap/gping/13/bin/gping", line 11, in <module>
    load_entry_point('pinggraph==1.0', 'console_scripts', 'gping')()
  File "/snap/gping/13/lib/python3.5/site-packages/gping/pinger.py", line 313, in run
    _run()
  File "/snap/gping/13/lib/python3.5/site-packages/gping/pinger.py", line 343, in _run
    plotted = plot(width, height, buff, host)
  File "/snap/gping/13/lib/python3.5/site-packages/gping/pinger.py", line 201, in plot
    blank=True
  File "/snap/gping/13/lib/python3.5/site-packages/gping/pinger.py", line 100, in box
    self.line(last_point, point, paint=paint, character=" " if blank else None)
  File "/snap/gping/13/lib/python3.5/site-packages/gping/pinger.py", line 79, in line
    self.vertical_line(character, from_.x, from_.y, to.y, paint)
  File "/snap/gping/13/lib/python3.5/site-packages/gping/pinger.py", line 72, in vertical_line
    self[column, y] = (next(data_iter), paint)
  File "/snap/gping/13/lib/python3.5/site-packages/gping/pinger.py", line 52, in __setitem__
    self.data[int(-y)][int(x)] = data
IndexError: list index out of range

**Comment by kn100** [comment]
Thanks!
