### ISSUE TITLE
snap permission error

### ISSUE THREAD

**Issue by vzaliva** [orf/gping#78]
Installed via `snap install gping` on Ubuntu and running gives me this error:

```
Traceback (most recent call last):
  File "/snap/gping/13/bin/gping", line 11, in <module>
    load_entry_point('pinggraph==1.0', 'console_scripts', 'gping')()
  File "/snap/gping/13/lib/python3.5/site-packages/gping/pinger.py", line 313, in run
    _run()
  File "/snap/gping/13/lib/python3.5/site-packages/gping/pinger.py", line 338, in _run
    for line in it(options):
  File "/snap/gping/13/lib/python3.5/site-packages/gping/pinger.py", line 251, in _inner
    ping = subprocess.Popen(args, stdout=subprocess.PIPE)
  File "/snap/gping/13/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/snap/gping/13/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
```

**Comment by orf** [comment]
Hey, the snap isn’t maintained and is not one of the installation methods listed in the README.
